// Flashcard data loader
// Add new course files here as they are created
// Each entry: { course, file (relative path), color }

(function() {
  // Inline data — loaded synchronously to avoid async issues with file:// or static servers
  window.FLASHCARD_DATA = [

    // ── STATISTIK ──────────────────────────────────────────────────────────
    {"id":"stat01-01","type":"qa","front":"Was ist die Formel für das Konfidenzintervall für μ bei BEKANNTEM σ?","back":"x̄ ± z_{α/2} · (σ/√n)\n\nz_{α/2}-Werte auswendig:\n• 90%-KI: z = 1.645\n• 95%-KI: z = 1.96\n• 99%-KI: z = 2.576","topic":"Schätztheorie","course":"Statistik","difficulty":2,"tags":["KI","z-Verteilung","Formel"]},
    {"id":"stat01-02","type":"qa","front":"Was ist die Formel für das Konfidenzintervall für μ bei UNBEKANNTEM σ?","back":"x̄ ± t_{α/2, n-1} · (s/√n)\n\nWichtig: t-Verteilung verwenden!\n• df = n - 1 Freiheitsgrade\n• t > z (breiter als bei bekanntem σ)\n• Ab n ≥ 30: t ≈ z (zentraler Grenzwertsatz)","topic":"Schätztheorie","course":"Statistik","difficulty":2,"tags":["KI","t-Verteilung","Formel"]},
    {"id":"stat01-03","type":"qa","front":"KI für den Anteilswert π — wie lautet die Formel?","back":"p ± z_{α/2} · √(p(1-p)/n)\n\n• p = Stichprobenanteil (x/n)\n• z_{α/2} = 1.96 für 95%-KI\n• Faustregel: n·p ≥ 5 und n·(1-p) ≥ 5 für Normalapproximation","topic":"Schätztheorie","course":"Statistik","difficulty":2,"tags":["KI","Anteilswert","Formel"]},
    {"id":"stat01-04","type":"qa","front":"Wie berechnet man den notwendigen Stichprobenumfang n für ein KI der Breite 2d?","back":"n = (z_{α/2} · σ / d)²\n\n• d = gewünschte halbe Intervalllbreite\n• Immer AUFRUNDEN!\n• Bei unbekanntem σ: Pilotstudie oder konservative Schätzung","topic":"Schätztheorie","course":"Statistik","difficulty":3,"tags":["Stichprobenumfang","KI","Formel"]},
    {"id":"stat01-05","type":"cloze","front":"Ein 95%-KI bedeutet: Das Intervall enthält in {{95%}} der Fälle den wahren Parameter μ — denn das {{Intervall}} ist zufällig, nicht {{μ}}.","back":"Ein 95%-KI bedeutet: Das Intervall enthält in 95% der Fälle den wahren Parameter μ — denn das Intervall ist zufällig, nicht μ.\n\nPrüfungsfalle: NICHT sagen 'μ liegt mit 95% Wahrscheinlichkeit im Intervall' — μ ist ein fixer (unbekannter) Wert!","topic":"Schätztheorie","course":"Statistik","difficulty":2,"tags":["KI","Interpretation"]},
    {"id":"stat02-01","type":"qa","front":"Prüfgrösse für den z-Test (H₀: μ = μ₀, σ bekannt)?","back":"z = (x̄ - μ₀) / (σ/√n)\n\nEntscheidungsregel:\n• Zweiseitig: |z| > z_{α/2} → H₀ ablehnen\n• Einseitig rechts: z > z_α → H₀ ablehnen\n• Einseitig links: z < -z_α → H₀ ablehnen","topic":"Hypothesentests","course":"Statistik","difficulty":2,"tags":["z-Test","Prüfgrösse","Formel"]},
    {"id":"stat02-02","type":"qa","front":"Prüfgrösse für den t-Test (H₀: μ = μ₀, σ unbekannt)?","back":"t = (x̄ - μ₀) / (s/√n)  mit df = n - 1\n\nWann t-Test statt z-Test?\n• σ² unbekannt (fast immer!)\n• Bei n ≥ 30 kaum Unterschied zur z-Verteilung\n• Bei n < 30: unbedingt t-Verteilung","topic":"Hypothesentests","course":"Statistik","difficulty":2,"tags":["t-Test","Prüfgrösse","Formel"]},
    {"id":"stat02-03","type":"qa","front":"Was ist α-Fehler (Typ I) und β-Fehler (Typ II)? Was ist Power?","back":"α-Fehler (Typ I): H₀ ist WAHR, wird aber abgelehnt → 'falscher Alarm'\nβ-Fehler (Typ II): H₀ ist FALSCH, wird aber beibehalten → 'verpasster Effekt'\n\nPower = 1 - β = Wahrscheinlichkeit, echten Effekt zu entdecken\n\nKonflikt: Kleines α → grosses β (man kann nicht beides minimieren)","topic":"Hypothesentests","course":"Statistik","difficulty":2,"tags":["Fehlertypen","Power","Konzept"]},
    {"id":"stat02-04","type":"cloze","front":"Der p-Wert ist {{P(Daten so extrem | H₀ wahr)}}. Er ist NICHT {{P(H₀ ist wahr)}}. Kleiner p-Wert = {{starke Evidenz gegen H₀}}.","back":"Der p-Wert ist P(Daten so extrem | H₀ wahr). Er ist NICHT P(H₀ ist wahr). Kleiner p-Wert = starke Evidenz gegen H₀.\n\nEntscheidung: p < α → H₀ ablehnen. p ≥ α → H₀ beibehalten (nicht beweisen!)","topic":"Hypothesentests","course":"Statistik","difficulty":3,"tags":["p-Wert","Interpretation"]},
    {"id":"stat02-05","type":"qa","front":"Wann verwirft man H₀? Nenne BEIDE Methoden.","back":"Methode 1 — Kritischer Wert: Testgrösse t/z > kritischer Wert → H₀ verwerfen\n\nMethode 2 — p-Wert: p < α → H₀ verwerfen\n\nBeide Methoden führen zum gleichen Ergebnis!\np < α  ⟺  |t| > t_{krit}","topic":"Hypothesentests","course":"Statistik","difficulty":2,"tags":["Entscheidungsregel"]},
    {"id":"stat03-01","type":"qa","front":"ANOVA F-Test: Wie lautet die Prüfgrösse?","back":"F = MSTR / MSE = [SSTR/(t-1)] / [SSE/(n-t)]\n\n• SSTR = Streuung ZWISCHEN Gruppen (systematisch)\n• SSE = Streuung INNERHALB Gruppen (Fehler)\n• t = Anzahl Gruppen, n = Gesamtgrösse\n• df₁ = t-1, df₂ = n-t","topic":"ANOVA","course":"Statistik","difficulty":3,"tags":["ANOVA","F-Test","Formel"]},
    {"id":"stat03-02","type":"qa","front":"Was sagen SST, SSTR, SSE? Wie hängen sie zusammen?","back":"SST = SSTR + SSE (immer!)\n\n• SST (Total): Gesamtstreuung, df = n-1\n• SSTR (Treatment): Zwischen Gruppen, df = t-1\n• SSE (Error): Innerhalb Gruppen, df = n-t\n\nAnalog zu Regression: Gesamtvariation = erklärt + unerklärt","topic":"ANOVA","course":"Statistik","difficulty":3,"tags":["ANOVA","Quadratsummen"]},
    {"id":"stat03-03","type":"qa","front":"Welche 3 Voraussetzungen braucht die ANOVA?","back":"1. Unabhängige Beobachtungen\n2. Normalverteilung innerhalb jeder Gruppe\n3. Varianzhomogenität: σ₁² = σ₂² = ... = σₜ²\n\nPrüfungsfalle: ANOVA testet nur OB mindestens zwei Gruppen verschieden sind — nicht WELCHE!","topic":"ANOVA","course":"Statistik","difficulty":2,"tags":["ANOVA","Voraussetzungen"]},
    {"id":"stat04-01","type":"qa","front":"Wie berechnet man β₁ (Steigung) und β₀ (Achsenabschnitt)?","back":"β₁ = Cov(X,Y) / Var(X) = Σ(xᵢ-x̄)(yᵢ-ȳ) / Σ(xᵢ-x̄)²\n\nβ₀ = ȳ - β₁ · x̄\n\nMerke: Regressionsgerade geht immer durch (x̄, ȳ)!\nKleinste-Quadrate-Methode minimiert Σ(yᵢ-ŷᵢ)²","topic":"Regression","course":"Statistik","difficulty":3,"tags":["Regression","β-Koeffizienten","Formel"]},
    {"id":"stat04-02","type":"qa","front":"Was ist R² und wie berechnet und interpretiert man es?","back":"R² = SSR/SST = 1 - SSE/SST\n\n• SST = SSR + SSE\n• SSR = erklärte Streuung\n• SSE = Residualstreuung\n\nInterpretation: R²=0.7 → '70% der Variation in Y wird durch X erklärt'\nHohes R² ≠ gutes Modell → Residualplot prüfen!","topic":"Regression","course":"Statistik","difficulty":2,"tags":["Regression","R²","Konzept"]},
    {"id":"stat04-03","type":"cloze","front":"Wenn β₁ signifikant (p < 0.05) ist, wird {{H₀: β₁ = 0}} abgelehnt — X hat einen {{signifikanten linearen Einfluss}} auf Y. Das beweist aber {{keine Kausalität}}.","back":"Wenn β₁ signifikant (p < 0.05) ist, wird H₀: β₁ = 0 abgelehnt — X hat einen signifikanten linearen Einfluss auf Y. Das beweist aber keine Kausalität.\n\nKausalität braucht ein Experiment (Randomisierung)!","topic":"Regression","course":"Statistik","difficulty":2,"tags":["Regression","Interpretation","Kausalität"]},
    {"id":"stat05-01","type":"qa","front":"Zentraler Grenzwertsatz (ZGS) — was besagt er und ab wann gilt er?","back":"X̄ ist NORMALVERTEILT mit μ und σ²/n — egal wie die GG verteilt ist.\n\nFaustregel: n ≥ 30\nStandardfehler: SE = σ/√n\n\nKonsequenz: Ab n ≥ 30 können wir immer den z-Test verwenden (approximativ). Der ZGS ist das Fundament der Statistik!","topic":"Stichprobenverteilungen","course":"Statistik","difficulty":2,"tags":["ZGS","Normalverteilung","Konzept"]},
    {"id":"stat05-02","type":"qa","front":"Was unterscheidet Standardabweichung (s) vom Standardfehler (SE)?","back":"Standardabweichung s: Streuung der EINZELNEN Beobachtungen\n• s = √[Σ(xᵢ-x̄)²/(n-1)]\n\nStandardfehler SE: Streuung des MITTELWERTS über viele Stichproben\n• SE = σ/√n  (oder s/√n bei unbekanntem σ)\n\nSE wird kleiner mit grösserem n → grössere Stichprobe = präzisere Schätzung","topic":"Stichprobenverteilungen","course":"Statistik","difficulty":2,"tags":["Standardfehler","SE","Konzept"]},
    {"id":"stat05-03","type":"qa","front":"Wann t-Verteilung, wann z-Verteilung? (3 Entscheidungsregeln)","back":"t-Verteilung wenn:\n1. σ unbekannt (fast immer in der Praxis!)\n2. n < 30\n3. GG normalverteilt\n\nz-Verteilung wenn:\n1. σ bekannt\n2. ODER n ≥ 30 (ZGS macht Annäherung gut genug)\n\nFaustregel: Im Zweifel t — es ist konservativer (breitere Verteilung, grösser kritischer Wert)","topic":"Verteilungen","course":"Statistik","difficulty":2,"tags":["t-Verteilung","z-Verteilung","Entscheidung"]},
    {"id":"stat06-01","type":"qa","front":"Was ist der Zweistichproben-t-Test? Wann gepaart vs. ungepaart?","back":"Test: μ₁ = μ₂? (zwei Gruppen gleich?)\n\nGepaart (gleiche Personen, vorher/nachher):\nt = d̄ / (s_d/√n), df = n-1\n\nUngepaart (verschiedene Personen):\nt = (x̄₁-x̄₂) / SE_diff, df ≈ n₁+n₂-2\n\nPrüfungsfalle: Gepaart vs. ungepaart richtig identifizieren — Vorher/Nachher = immer gepaart!","topic":"Hypothesentests","course":"Statistik","difficulty":3,"tags":["Zweistichproben","t-Test","Formel"]},
    {"id":"stat06-02","type":"why","front":"Warum dividiert man bei der Stichprobenvarianz durch (n-1) und nicht durch n?","back":"Weil x̄ bereits aus denselben Daten geschätzt wurde → 1 Freiheitsgrad verloren.\n\nDivision durch (n-1) macht s² zum UNVERZERRTEN Schätzer von σ².\nDivision durch n würde σ² systematisch unterschätzen.\n\nMerke: n-1 = 'Bessel-Korrektur'. df = n-1 'bezahlt' für die Schätzung von μ.","topic":"Schätztheorie","course":"Statistik","difficulty":3,"tags":["Stichprobenvarianz","Freiheitsgrade","Konzept"]},
    {"id":"stat06-03","type":"qa","front":"Was sind Freiheitsgrade (df) — und welche gelten wo?","back":"df = freie Datenpunkte - geschätzte Parameter\n\n• t-Test (einstichprobig): df = n-1\n• t-Test (zweistichprobig, ungepaart): df ≈ n₁+n₂-2\n• ANOVA Between: df = t-1\n• ANOVA Within: df = n-t\n• Einfache Regression (Residual): df = n-2\n\ndf bestimmt den kritischen Wert in der Tabelle!","topic":"Allgemein","course":"Statistik","difficulty":3,"tags":["Freiheitsgrade","df","Überblick"]}
  ];
})();
